name: Monitoring Stack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy_monitoring_stack:
    runs-on: ubuntu-latest
    env:
      CONFIGU_ORG: ${{ secrets.CONFIGU_ORG }}
      CONFIGU_TOKEN: ${{ secrets.CONFIGU_TOKEN }}
    #   TF_TOKEN_backend_api_env0_com: ${{ secrets.TF_TOKEN_backend_api_env0_com }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Configu CLI
      uses: configu/setup-cli-action@v1

    - name: Export configurations
      run: configu eval --store 'configu' --set 'Development/Monitoring' --schema './monitoring.cfgu.json' | configu export --format 'TerraformTfvars' > "./Terraform/var.auto.tfvars"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.7'

    - name: Terraform Init and Apply
      run: |
        terraform init
        terraform apply -auto-approve
      working-directory: ./Terraform

    - name: Generate SSH Key File
      run: terraform output -raw private_key > /tmp/myKey.pem
      working-directory: ./Terraform

    - name: Set Public IP as Env Var
      run: |
        {
            echo "PUBLIC_IP<<EOF"
            echo $(terraform output public_ip)
            echo "EOF"
        } >> "$GITHUB_ENV"
      working-directory: ./Terraform

    - name: Use Public IP
      run: |
        echo "The public IP is $PUBLIC_IP"
    
    - name: Set Permission for SSH Key
      run: chmod 400 /tmp/myKey.pem

    - name: Add Terraform IP to Configu
      run: configu upsert --store 'configu' --set 'Development/Monitoring' --schema './monitoring.cfgu.json' -c 'ip=$PUBLIC_IP'

    - name: Update Ansible Inventory with Public IP
      run: sed -i "s/<placeholder_app>/$(terraform output -raw public_ip)/g" Ansible/inventory

    - name: Install Ansible
      run: pip3 install --user ansible

    - name: List Files (Debugging)
      run: ls -lah

    - name: Show Ansible Inventory (Debugging)
      run: cat Ansible/inventory

    - name: Run Ansible Playbook
      run: cd Ansible && ansible-playbook --private-key /tmp/myKey.pem -i inventory monitoringPlaybook.yaml
