name: Destroy Monitoring Stack Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'development'
        type: choice
        options:
          - production
          - development

jobs:
  destroy_infra:
    runs-on: ubuntu-latest
    env:
      TF_LOG: ERROR
      CONFIGU_ORG: ${{ secrets.CONFIGU_ORG }}
      CONFIGU_TOKEN: ${{ secrets.CONFIGU_TOKEN }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Export configurations for Development
      if: ${{ github.event.inputs.environment == 'development' }}
      run: configu eval --store 'configu' --set 'Development/Monitoring' --schema './monitoring.cfgu.json' | configu export --format 'TerraformTfvars' > "./Terraform/var.auto.tfvars"

    - name: Export configurations for Production
      if: ${{ github.event.inputs.environment == 'production' }}
      run: configu eval --store 'configu' --set 'Production/Monitoring' --schema './monitoring.cfgu.json' | configu export --format 'TerraformTfvars' > "./Terraform/var.auto.tfvars"
      
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.7'

    - name: Initialize Terraform with Dynamic Backend Config
      run: terraform init
      working-directory: ./Terraform
      env:
        TF_CLI_ARGS_init: -backend-config=${{ github.event.inputs.environment }}.hcl
      
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ./Terraform